(setq geiser-active-implementations '(guile chez chibi))
(setq geiser-default-implementation 'guile)
(setq geiser-mode-smart-tab-p t)
(defun my-scheme-hook ()
  (paredit-mode 1))
(add-hook 'scheme-mode-hook (function my-scheme-hook))
(setq auto-mode-alist (remove '("\\.rkt\\'" . scheme-mode) auto-mode-alist))
