(setq geiser-active-implementations '(guile racket chez))
(setq geiser-default-implementation 'racket)
(setq geiser-mode-smart-tab-p t)
(defun my-scheme-hook ()
  (paredit-mode 1))
(add-hook 'scheme-mode-hook (function my-scheme-hook))
